# Generated by Django 2.2 on 2021-09-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='reg',
        ),
    ]
