# Generated by Django 2.2 on 2021-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210901_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
