# Generated by Django 2.2 on 2021-08-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='categ',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
