# Generated by Django 2.2 on 2021-08-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_auto_20210820_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=23, unique=True)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
