# Generated by Django 2.2 on 2021-09-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('prodt',), 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
